services:
  gama:
    image: gamaplatform/gama
    networks:
      - shared_network
    volumes:
      - ./CS_CityScope_GAMA:/CS_CityScope_GAMA
    command: ["gama", "-socket", "8000"]
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  brix:
    build: .
    networks:
      - shared_network
    environment:
      - CityIO_IMAGE=cityio
      - Gama_IMAGE=gama
    volumes:
      - ./scripts:/scripts
    command: ["/brix/bin/python", "/scripts/brix.py"]
    depends_on:
      gama:
        condition: service_healthy

networks:
  shared_network:
    external: true
