services:
  gama:
    image: gamaplatform/gama
    volumes:
      - ./CS_CityScope_GAMA:/CS_CityScope_GAMA
    command: ["gama", "-socket", "8000"]
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  brix:
    build: .
    working_dir: /app
    environment:
      - CityIO_IMAGE=cityio
      - Gama_IMAGE=gama
    volumes:
      - ./scripts:/app/scripts
    command: ["/app/brix/bin/python", "/app/scripts/brix.py"]
    depends_on:
      gama:
        condition: service_healthy
