services:
  gama:
    image: gamaplatform/gama
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./CS_CityScope_GAMA:/working_dir
    command: ["gama", "-socket", "8000"]

  brix:
    build: .
    working_dir: /app
    environment:
      - CityIO_IMAGE=cityio
    volumes:
      - ./scripts:/app/scripts
    command: ["/app/brix/bin/python", "/app/scripts/brix.py"]
