services:
  gama:
    image: gamaplatform/gama
    volumes:
      - ./CS_CityScope_GAMA:/CS_CityScope_GAMA
    command: ["gama", "-socket", "8000"]

  brix:
    build: .
    working_dir: /app
    environment:
      - CityIO_IMAGE=cityio
    volumes:
      - ./scripts:/app/scripts
    command: ["/app/brix/bin/python", "/app/scripts/brix.py"]
